.SUFFIXES:
.SUFFIXES: .o .f .c .cpp

# these are cpp preprocessing flags (cpp) as opposed to (cxx) the c++ compiler

.f.o:
	$(F77) $(FFLAGS) -c $< -o $@
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
.cpp.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

SHELL = /bin/sh

LIBNAME = fv

# Typical options here include:
#
# -O3 (optimization)
# -g  (debugging)
# -pg (profiling)
DEBUGOPT      = -O3 -fopenmp
#DEBUGOPT      = -O3
#DEBUGOPT      = -g -pg

# Typical option here includes:
# -Wall (turn on warnings )
CXXWARNINGS   = 

RM            = rm -f
MAKE          = gmake
AR	          = ar
LD            = ld

F77           = gfortran
FFLAGS        = $(DEBUGOPT) $(FFLAGS_EXTRA)

CC            = gcc
CFLAGS        = $(DEBUGOPT) $(CFLAGS_EXTRA)

CXX           = g++
CXXFLAGS      =	$(DEBUGOPT) $(CXXWARNINGS) $(CXXFLAGS_EXTRA)

CPPFLAGS      =  -I. $(CPPFLAGS_EXTRA)

# capital -L flags
LDFLAGS       = $(LDFLAGS_EXTRA) -fopenmp

# lowercase -l flags
LDLIBS        = $(LDLIBS_EXTRA) -lm

